name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  job:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact-name: Linux
          #- os: macos-11
          # artifact-name: Darwin
          #- os: windows-2022
          #  artifact-name: Win64 
    runs-on: ${{ matrix.os }} 
    continue-on-error: true
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install .NET 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Display dotnet info
        run: dotnet --list-sdks  
      - name: Run tests
        run: dotnet test src/ReverseMarkdown.Test/ReverseMarkdown.Test.csproj --framework net8.0

